-- Activar siempre al principio
SET SERVEROUTPUT ON;

-- Pagina 218
DECLARE
    V_NUM_EMPLEADOS NUMBER(2);
BEGIN
    INSERT INTO DEPART VALUES (99, 'D PROVISIONAL',NULL);
    UPDATE EMPLE SET DEPT_NO = 99 
        WHERE EMPLE.DEPT_NO = 20;
    V_NUM_EMPLEADOS := SQL%ROWCOUNT;
    DELETE FROM DEPART 
        WHERE DEPART.DEPT_NO = 20;
    DBMS_OUTPUT.PUT_LINE(V_NUM_EMPLEADOS || ' EMPLEADOS UBICADOS EN PROVISIONAL');
EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR (-20000, 'ERROR EN LA APLICACIÓN');
END;
/

-- Pagina 222
DECLARE 
    V_APP_EMPLE VARCHAR2(10);
    V_OF_EMPLE VARCHAR2(10);
BEGIN
    SELECT APELLIDO, OFICIO INTO V_APP_EMPLE, V_OF_EMPLE
        FROM EMPLE
        WHERE EMPLE.EMP_NO = 7900;
    DBMS_OUTPUT.PUT_LINE(V_APP_EMPLE || ' - ' || V_OF_EMPLE);
END;
/
