SET SERVEROUTPUT ON;

CLEAR SCR 
DISCONNECT  
-- Conectarse como SYS y crear otro usuario
CONNECT SYS AS SYSDBA; 

DROP USER GUILLERMO; 

-- Usuario con el que trabajaremos
CREATE USER GUILLERMO IDENTIFIED BY Guillermo; 
GRANT DBA TO GUILLERMO; 
GRANT ALL PRIVILEGES TO GUILLERMO; 


REM *** INSERCION DE TABLAS EN EL USUARIO GUILLERMO ***

-- GRANT SELECT, INSERT, UPDATE, DELETE ON BANCOS TO GUILLERMO;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON SUCURSALES TO GUILLERMO;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON CUENTAS TO GUILLERMO;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON MOVIMIENTOS TO GUILLERMO;

REM *** PASANDO AL USUARIO GUILLERMO *** 

CLEAR SCR 
DISCONNECT

REM ***
REM SE VA A CONECTAR AL SIGUIENTE USUARIO
REM USUARIO: GUILLERMO 
REM CONTRASEÑA: Guillermo 
REM ****

CONNECT GUILLERMO

REM *** CREACION DE OBJETOS ***

-- OBJETO BANCOS
CREATE OR REPLACE TYPE BANCOS_OBJ AS OBJECT (
  COD_BANCO   NUMBER(4),
  NF_BANCO    VARCHAR2(10),
  NOMBRE_BANC VARCHAR2(30),
  DOM_FISCAL  VARCHAR(35),
  POBLACION   VARCHAR(35),
  MEMBER FUNCTION getCodBanco RETURN NUMBER,
  MEMBER PROCEDURE setCodBanco(cod_banco NUMBER),
  MEMBER FUNCTION getNfBanco RETURN VARCHAR2,
  MEMBER PROCEDURE setNfBanco(nf_banco VARCHAR2),
  MEMBER FUNCTION getNombreBanc RETURN VARCHAR2,
  MEMBER PROCEDURE setNombreBanc(nombre_banc VARCHAR2),
  MEMBER FUNCTION getDomFiscal RETURN VARCHAR,
  MEMBER PROCEDURE setDomFiscal(dom_fiscal VARCHAR),
  MEMBER FUNCTION getPoblacion RETURN VARCHAR,
  MEMBER PROCEDURE setPoblacion(poblacion VARCHAR),
  MEMBER PROCEDURE toString
);
/

CREATE OR REPLACE TYPE BODY BANCOS_OBJ AS
  MEMBER FUNCTION getCodBanco RETURN NUMBER IS
    BEGIN RETURN COD_BANCO;
  END getCodBanco;

  MEMBER PROCEDURE setCodBanco(cod_banco NUMBER) IS
    BEGIN
      SELF.COD_BANCO := cod_banco;
  END setCodBanco;

  MEMBER FUNCTION getNfBanco RETURN VARCHAR2 IS
    BEGIN RETURN NF_BANCO;
  END getNfBanco;

  MEMBER PROCEDURE setNfBanco(nf_banco VARCHAR2) IS
    BEGIN
      SELF.NF_BANCO := nf_banco;
  END setNfBanco;

  MEMBER FUNCTION getNombreBanc RETURN VARCHAR2 IS
    BEGIN RETURN NOMBRE_BANC;
  END getNombreBanc;

  MEMBER PROCEDURE setNombreBanc(nombre_banc VARCHAR2) IS
    BEGIN
      SELF.NOMBRE_BANC := nombre_banc;
  END setNombreBanc;

  MEMBER FUNCTION getDomFiscal RETURN VARCHAR IS
    BEGIN RETURN DOM_FISCAL;
  END getDomFiscal;

  MEMBER PROCEDURE setDomFiscal(dom_fiscal VARCHAR) IS 
    BEGIN
      SELF.DOM_FISCAL := dom_fiscal;
  END setDomFiscal;

  MEMBER FUNCTION getPoblacion RETURN VARCHAR IS 
    BEGIN RETURN POBLACION;
  END getPoblacion;

  MEMBER PROCEDURE setPoblacion(poblacion VARCHAR) IS
    BEGIN
      SELF.POBLACION := poblacion;
  END setPoblacion;
  
  MEMBER PROCEDURE toString IS
    BEGIN
      DBMS_OUTPUT.PUT_LINE('COD_BANCO ' || COD_BANCO);
      DBMS_OUTPUT.PUT_LINE('NF_BANCO ' || NF_BANCO);
      DBMS_OUTPUT.PUT_LINE('NOMBRE_BANC ' || NOMBRE_BANC);
      DBMS_OUTPUT.PUT_LINE('DOM_FISCAL ' || DOM_FISCAL);
      DBMS_OUTPUT.PUT_LINE('POBLACION ' || POBLACION);
    END toString;
END;
/

-- OBJETO SUCURSALES
CREATE OR REPLACE TYPE SUCURSALES_OBJ AS OBJECT (
  COD_BANCO   NUMBER(4),
  COD_SUCUR   NUMBER(4),
  NOMBRE_SUC  VARCHAR2(35),
  DIREC_SUC   VARCHAR2(35),
  LOC_SUC     VARCHAR2(20),
  PROV_SUC    VARCHAR2(20),
  MEMBER FUNCTION getCodBanco RETURN NUMBER,
  MEMBER PROCEDURE setCodBanco(cod_banco NUMBER),
  MEMBER FUNCTION getCodSucur RETURN NUMBER,
  MEMBER PROCEDURE setCodSucur(cod_sucur NUMBER),
  MEMBER FUNCTION getNombreSuc RETURN VARCHAR2,
  MEMBER PROCEDURE setNombreSuc(nombre_suc VARCHAR2),
  MEMBER FUNCTION getDirecSuc RETURN VARCHAR2,
  MEMBER PROCEDURE setDirecSuc(direc_suc VARCHAR2),
  MEMBER FUNCTION getLocSuc RETURN VARCHAR2,
  MEMBER PROCEDURE setLocSuc(loc_suc VARCHAR2),
  MEMBER FUNCTION getProvSuc RETURN VARCHAR2,
  MEMBER PROCEDURE setProvSuc(prov_suc VARCHAR2),
  MEMBER PROCEDURE toString
);
/

CREATE OR REPLACE TYPE BODY SUCURSALES_OBJ AS
  MEMBER FUNCTION getCodBanco RETURN NUMBER IS
    BEGIN RETURN COD_BANCO;
  END getCodBanco;

  MEMBER PROCEDURE setCodBanco(cod_banco NUMBER) IS
    BEGIN SELF.COD_BANCO := cod_banco;
  END setCodBanco;

  MEMBER FUNCTION getCodSucur RETURN NUMBER IS
    BEGIN RETURN COD_SUCUR;
  END getCodSucur;

  MEMBER PROCEDURE setCodSucur(cod_sucur NUMBER) IS
    BEGIN SELF.COD_SUCUR := cod_sucur;
  END setCodSucur;

  MEMBER FUNCTION getNombreSuc RETURN VARCHAR2 IS
    BEGIN RETURN NOMBRE_SUC;
  END getNombreSuc;

  MEMBER PROCEDURE setNombreSuc(nombre_suc VARCHAR2) IS
    BEGIN SELF.NOMBRE_SUC := nombre_suc;
  END setNombreSuc;

  MEMBER FUNCTION getDirecSuc RETURN VARCHAR2 IS
    BEGIN RETURN DIREC_SUC;
  END getDirecSuc; 

  MEMBER PROCEDURE setDirecSuc(direc_suc VARCHAR2) IS
    BEGIN SELF.DIREC_SUC := direc_suc;
  END setDirecSuc;

  MEMBER FUNCTION getLocSuc RETURN VARCHAR2 IS
    BEGIN RETURN LOC_SUC;
  END getLocSuc;

  MEMBER PROCEDURE setLocSuc(loc_suc VARCHAR2) IS
    BEGIN SELF.LOC_SUC := loc_suc;
  END setLocSuc;

  MEMBER FUNCTION getProvSuc RETURN VARCHAR2 IS
    BEGIN RETURN PROV_SUC;
  END getProvSuc;

  MEMBER PROCEDURE setProvSuc(prov_suc VARCHAR2) IS
    BEGIN SELF.PROV_SUC := prov_suc;
  END setProvSuc;

  MEMBER PROCEDURE toString IS
    BEGIN
      DBMS_OUTPUT.PUT_LINE('COD_BANCO ' || COD_BANCO);
      DBMS_OUTPUT.PUT_LINE('COD_SUCUR ' || COD_SUCUR);
      DBMS_OUTPUT.PUT_LINE('NOMBRE_SUC ' || NOMBRE_SUC);
      DBMS_OUTPUT.PUT_LINE('DIREC_SUC ' || DIREC_SUC);
      DBMS_OUTPUT.PUT_LINE('LOC_SUC ' || LOC_SUC);
      DBMS_OUTPUT.PUT_LINE('PROV_SUC ' || PROV_SUC);
    END toString;
END;
/

-- OBJETO CUENTAS
CREATE OR REPLACE TYPE CUENTAS_OBJ AS OBJECT (
  COD_BANCO   NUMBER(4),
  COD_SUCUR   NUMBER(4),
  NUM_CTA     NUMBER(10),
  FECHA_ALTA  DATE,
  NOMBRE_CTA  VARCHAR2(35),
  DIREC_CTA   VARCHAR2(35),
  POBLA_CTA   VARCHAR2(20),
  SALDO_DEBE  NUMBER(10),
  SALDO_HABER NUMBER(10),
  MEMBER FUNCTION getCodBanco RETURN NUMBER,
  MEMBER PROCEDURE setCodBanco(cod_banco NUMBER),
  MEMBER FUNCTION getCodSucur RETURN NUMBER,
  MEMBER PROCEDURE setCodSucur(cod_sucur NUMBER),
  MEMBER FUNCTION getNumCta RETURN NUMBER,
  MEMBER PROCEDURE setNumCta(num_cta NUMBER),
  MEMBER FUNCTION getFechaAlta RETURN DATE,
  MEMBER PROCEDURE setFechaAlta(fecha_alta DATE),
  MEMBER FUNCTION getNombreCta RETURN VARCHAR2,
  MEMBER PROCEDURE setNombreCta(nombre_cta VARCHAR2),
  MEMBER FUNCTION getDirectCta RETURN VARCHAR2,
  MEMBER PROCEDURE setDirectCta(direct_cta VARCHAR2),
  MEMBER FUNCTION getPoblaCta RETURN VARCHAR2,
  MEMBER PROCEDURE setPoblaCta(pobla_cta VARCHAR2),
  MEMBER FUNCTION getSaldoDebe RETURN NUMBER,
  MEMBER PROCEDURE setSaldoDebe(saldo_debe NUMBER),
  MEMBER FUNCTION getSaldoHaber RETURN NUMBER,
  MEMBER PROCEDURE setSaldoHaber(saldo_haber NUMBER),
  MEMBER PROCEDURE toString
);
/

CREATE OR REPLACE TYPE BODY CUENTAS_OBJ AS
  MEMBER FUNCTION getCodBanco RETURN NUMBER IS
    BEGIN RETURN COD_BANCO;
  END getCodBanco;

  MEMBER PROCEDURE setCodBanco(cod_banco NUMBER) IS
    BEGIN SELF.COD_BANCO:= cod_banco;
  END setCodBanco;

  MEMBER FUNCTION getCodSucur RETURN NUMBER IS
    BEGIN RETURN COD_SUCUR;
  END getCodSucur;

  MEMBER PROCEDURE setCodSucur(cod_sucur NUMBER) IS
    BEGIN SELF.COD_SUCUR:= cod_sucur;
  END setCodSucur;

  MEMBER FUNCTION getNumCta RETURN NUMBER IS
    BEGIN RETURN NUM_CTA;
  END getNumCta;

  MEMBER PROCEDURE setNumCta(num_cta NUMBER) IS
  BEGIN SELF.NUM_CTA:= num_cta;
  END setNumCta;

  MEMBER FUNCTION getFechaAlta RETURN DATE IS
    BEGIN RETURN FECHA_ALTA;
  END getFechaAlta;

  MEMBER PROCEDURE setFechaAlta(fecha_alta DATE) IS
    BEGIN SELF.FECHA_ALTA:= fecha_alta;
  END setFechaAlta;

  MEMBER FUNCTION getNombreCta RETURN VARCHAR2 IS
    BEGIN RETURN NOMBRE_CTA;
  END getNombreCta;

  MEMBER PROCEDURE setNombreCta(nombre_cta VARCHAR2) IS
    BEGIN SELF.NOMBRE_CTA:= nombre_cta;
  END setNombreCta;

  MEMBER FUNCTION getDirectCta RETURN VARCHAR2 IS
    BEGIN RETURN DIREC_CTA;
  END getDirectCta;

  MEMBER PROCEDURE setDirectCta(direct_cta VARCHAR2) IS
    BEGIN SELF.DIREC_CTA:= direct_cta;
  END setDirectCta;

  MEMBER FUNCTION getPoblaCta RETURN VARCHAR2 IS
    BEGIN RETURN POBLA_CTA;
  END getPoblaCta;

  MEMBER PROCEDURE setPoblaCta(pobla_cta VARCHAR2) IS
    BEGIN SELF.POBLA_CTA:= pobla_cta;
  END setPoblaCta;

  MEMBER FUNCTION getSaldoDebe RETURN NUMBER IS
    BEGIN RETURN SALDO_DEBE;
  END getSaldoDebe;

  MEMBER PROCEDURE setSaldoDebe(saldo_debe NUMBER) IS
    BEGIN SELF.SALDO_DEBE:= saldo_debe;
    END setSaldoDebe;

  MEMBER FUNCTION getSaldoHaber RETURN NUMBER IS
    BEGIN RETURN SALDO_HABER;
  END getSaldoHaber;

  MEMBER PROCEDURE setSaldoHaber(saldo_haber NUMBER) IS
    BEGIN SELF.SALDO_HABER:= saldo_haber;
  END setSaldoHaber;

  MEMBER PROCEDURE toString IS
    BEGIN
      DBMS_OUTPUT.PUT_LINE('COD_BANCO ' || COD_BANCO);
      DBMS_OUTPUT.PUT_LINE('COD_SUCUR ' || COD_SUCUR);
      DBMS_OUTPUT.PUT_LINE('NUM_CTA ' || NUM_CTA);
      DBMS_OUTPUT.PUT_LINE('FECHA_ALTA ' || FECHA_ALTA);
      DBMS_OUTPUT.PUT_LINE('NOMBRE_CTA ' || NOMBRE_CTA);
      DBMS_OUTPUT.PUT_LINE('DIREC_CTA ' || DIREC_CTA);
      DBMS_OUTPUT.PUT_LINE('POBLA_CTA ' || POBLA_CTA);
      DBMS_OUTPUT.PUT_LINE('SALDO_DEBE ' || SALDO_DEBE);
      DBMS_OUTPUT.PUT_LINE('SALDO_HABER ' || SALDO_HABER);
    END toString;
END;
/

-- OBJETO MOVIMIENTOS
CREATE OR REPLACE TYPE MOVIMIENTOS_OBJ AS OBJECT (
  COD_BANCO   NUMBER(4),
  COD_SUCUR   NUMBER(4),
  NUM_CTA     NUMBER(10),
  FECHA_MOV   DATE,
  TIPO_MOV    CHAR(1),
  IMPORTE     NUMBER(10),
  MEMBER FUNCTION getCodBanco RETURN NUMBER,
  MEMBER PROCEDURE setCodBanco(cod_banco NUMBER),
  MEMBER FUNCTION getCodSucur RETURN NUMBER,
  MEMBER PROCEDURE setCodSucur(cod_sucur NUMBER),
  MEMBER FUNCTION getNumCta RETURN NUMBER,
  MEMBER PROCEDURE setNumCta(num_cta NUMBER),
  MEMBER FUNCTION getFechaMov RETURN DATE,
  MEMBER PROCEDURE setFechaMov(fecha_mov DATE),
  MEMBER FUNCTION getTipoMov RETURN CHAR,
  MEMBER PROCEDURE setTipoMov(tipo_mov CHAR),
  MEMBER FUNCTION getImporte RETURN NUMBER,
  MEMBER PROCEDURE setImporte(importe NUMBER),
  MEMBER PROCEDURE toString
);
/

CREATE OR REPLACE TYPE BODY MOVIMIENTOS_OBJ AS
  MEMBER FUNCTION getCodBanco RETURN NUMBER IS
    BEGIN RETURN COD_BANCO;
  END getCodBanco;

  MEMBER PROCEDURE setCodBanco(cod_banco NUMBER) IS
    BEGIN SELF.COD_BANCO := cod_banco;
  END setCodBanco;
  
  MEMBER FUNCTION getCodSucur RETURN NUMBER IS
    BEGIN RETURN COD_SUCUR;
  END getCodSucur;

  MEMBER PROCEDURE setCodSucur(cod_sucur NUMBER) IS
    BEGIN SELF.COD_SUCUR := cod_sucur;
  END setCodSucur;
  
  MEMBER FUNCTION getNumCta RETURN NUMBER IS
    BEGIN RETURN NUM_CTA;
  END getNumCta;

  MEMBER PROCEDURE setNumCta(num_cta NUMBER) IS
    BEGIN SELF.NUM_CTA := num_cta;
  END setNumCta;
  
  MEMBER FUNCTION getFechaMov RETURN DATE IS
    BEGIN RETURN FECHA_MOV;
  END getFechaMov;

  MEMBER PROCEDURE setFechaMov(fecha_mov DATE) IS
    BEGIN SELF.FECHA_MOV := fecha_mov;
  END setFechaMov;
  
  MEMBER FUNCTION getTipoMov RETURN CHAR IS
    BEGIN RETURN TIPO_MOV;
  END getTipoMov;

  MEMBER PROCEDURE setTipoMov(tipo_mov CHAR) IS
    BEGIN SELF.TIPO_MOV := tipo_mov;
  END setTipoMov;
  
  MEMBER FUNCTION getImporte RETURN NUMBER IS
    BEGIN RETURN IMPORTE;
  END getImporte;

  MEMBER PROCEDURE setImporte(importe NUMBER) IS
    BEGIN SELF.IMPORTE := importe;
  END setImporte;

  MEMBER PROCEDURE toString IS
    BEGIN
      DBMS_OUTPUT.PUT_LINE('COD_BANCO ' || COD_BANCO);
      DBMS_OUTPUT.PUT_LINE('COD_SUCUR ' || COD_SUCUR);
      DBMS_OUTPUT.PUT_LINE('NUM_CTA ' || NUM_CTA);
      DBMS_OUTPUT.PUT_LINE('FECHA_MOV ' || FECHA_MOV);
      DBMS_OUTPUT.PUT_LINE('TIPO_MOV ' || TIPO_MOV);
      DBMS_OUTPUT.PUT_LINE('IMPORTE ' || IMPORTE);
    END toString;
END;
/


REM *** CREACION DE OPERACIONES CUD ***

-- BANCOS_OBJ
CREATE OR REPLACE PROCEDURE INSERT_BANCOS(banco BANCOS_OBJ)
  IS
    e_noInsert EXCEPTION;
  BEGIN 
  INSERT INTO BANCOS (COD_BANCO, NF_BANCO, NOMBRE_BANC, DOM_FISCAL, POBLACION) 
    VALUES(banco.getCodBanco, banco.getNfBanco, banco.getNombreBanc, banco.getDomFiscal, banco.getPoblacion);

  IF SQL%ROWCOUNT = 0 THEN
    RAISE e_noInsert;
  END IF;
  
  
  EXCEPTION 
    WHEN DUP_VAL_ON_INDEX THEN
      RAISE_APPLICATION_ERROR(-20000, 'NO SE HA INSERTADO EN TABLA BANCOS, INDICE DUPLICADO');
      
    WHEN e_noInsert THEN
      RAISE_APPLICATION_ERROR(-20000, 'NO SE HA PODIDO INSERTAR EN TABLA BANCOS');
      
    WHEN OTHERS THEN
      RAISE_APPLICATION_ERROR(-20000, 'HA HABIDO UN ERROR: - ' || SQLCODE || ' -ERROR- ' || SQLERRM); 
      
END INSERT_BANCOS;
/

CREATE OR REPLACE PROCEDURE UPDATE_BANCOS(banco BANCOS_OBJ)
  IS
    e_noUpdate EXCEPTION;
  BEGIN
    UPDATE BANCOS 
      SET NF_BANCO = banco.getNfBanco, NOMBRE_BANC = banco.getNombreBanc, DOM_FISCAL = banco.getDomFiscal, POBLACION = banco.getPoblacion
      WHERE COD_BANCO = banco.getCodBanco;
  
  IF SQL%ROWCOUNT = 0 THEN
    RAISE e_noUpdate;
  END IF;
  
  
  EXCEPTION 
    WHEN e_noUpdate THEN
      RAISE_APPLICATION_ERROR(-20000, 'NO SE HA PODIDO ACTUALIZAR EN TABLA BANCOS');
      
    WHEN OTHERS THEN
      RAISE_APPLICATION_ERROR(-20000, 'HA HABIDO UN ERROR: - ' || SQLCODE || ' -ERROR- ' || SQLERRM); 
      
END UPDATE_BANCOS;
/

CREATE OR REPLACE PROCEDURE DELETE_BANCOS(v_cod_banco IN BANCOS.COD_BANCO%TYPE)
  IS
    e_noDelete EXCEPTION;
  BEGIN
    DELETE FROM BANCOS
      WHERE COD_BANCO = v_cod_banco;
     
  IF SQL%ROWCOUNT = 0 THEN
    RAISE e_noDelete;
  END IF;
   

  EXCEPTION 
    WHEN e_noDelete THEN
      RAISE_APPLICATION_ERROR(-20000, 'NO SE HA PODIDO BORRAR EN TABLA BANCOS');
      
    WHEN OTHERS THEN
      RAISE_APPLICATION_ERROR(-20000, 'HA HABIDO UN ERROR: - ' || SQLCODE || ' -ERROR- ' || SQLERRM); 
      
END DELETE_BANCOS;
/

-- SUCURSALES_OBJ
CREATE OR REPLACE PROCEDURE INSERT_SUCURSALES(sucursal SUCURSALES_OBJ)
  IS
    e_noInsert EXCEPTION;
  BEGIN 
  INSERT INTO SUCURSALES (COD_BANCO, COD_SUCUR, NOMBRE_SUC, DIREC_SUC, LOC_SUC, PROV_SUC)  
    VALUES(sucursal.getCodBanco, sucursal.getCodSucur, sucursal.getNombreSuc, sucursal.getDirecSuc, sucursal.getLocSuc, sucursal.getProvSuc);

  IF SQL%ROWCOUNT = 0 THEN
    RAISE e_noInsert;
  END IF;
  
  
  EXCEPTION 
    WHEN e_noInsert THEN
      RAISE_APPLICATION_ERROR(-20000, 'NO SE HA PODIDO INSERTAR EN TABLA SUCURSALES');
      
    WHEN OTHERS THEN
      RAISE_APPLICATION_ERROR(-20000, 'HA HABIDO UN ERROR: - ' || SQLCODE || ' -ERROR- ' || SQLERRM); 
      
END INSERT_SUCURSALES;
/

CREATE OR REPLACE PROCEDURE UPDATE_SUCURSALES(sucursal SUCURSALES_OBJ)
  IS
    e_noUpdate EXCEPTION;
  BEGIN 
    UPDATE SUCURSALES 
      SET NOMBRE_SUC = sucursal.getNombreSuc, DIREC_SUC = sucursal.getDirecSuc, LOC_SUC = sucursal.getLocSuc, PROV_SUC = sucursal.getProvSuc 
      WHERE COD_BANCO = sucursal.getCodBanco AND COD_SUCUR = sucursal.getCodSucur;
    
  IF SQL%ROWCOUNT = 0 THEN
    RAISE e_noUpdate;
  END IF;
  
  
  EXCEPTION 
    WHEN e_noUpdate THEN
      RAISE_APPLICATION_ERROR(-20000, 'NO SE HA PODIDO ACTUALIZAR EN TABLA SUCURSALES');
      
    WHEN OTHERS THEN
      RAISE_APPLICATION_ERROR(-20000, 'HA HABIDO UN ERROR: - ' || SQLCODE || ' -ERROR- ' || SQLERRM); 
      
END UPDATE_SUCURSALES;
/

CREATE OR REPLACE PROCEDURE DELETE_SUCURSALES(
  v_cod_banco IN SUCURSALES.COD_BANCO%TYPE,
  v_cod_sucur IN SUCURSALES.COD_SUCUR%TYPE)
  IS
    e_noDelete EXCEPTION;
  BEGIN
    DELETE FROM SUCURSALES
      WHERE COD_BANCO = v_cod_banco AND COD_SUCUR = v_cod_sucur;
     
  IF SQL%ROWCOUNT = 0 THEN
    RAISE e_noDelete;
  END IF;
   

  EXCEPTION 
    WHEN e_noDelete THEN
      RAISE_APPLICATION_ERROR(-20000, 'NO SE HA PODIDO BORRAR EN TABLA SUCURSALES');
      
    WHEN OTHERS THEN
      RAISE_APPLICATION_ERROR(-20000, 'HA HABIDO UN ERROR: - ' || SQLCODE || ' -ERROR- ' || SQLERRM); 
      
END DELETE_SUCURSALES;
/

-- CUENTAS_OBJ
CREATE OR REPLACE PROCEDURE INSERT_CUENTAS(cuentas CUENTAS_OBJ)
  IS
    e_noInsert EXCEPTION;
  BEGIN 
  INSERT INTO CUENTAS (COD_BANCO, COD_SUCUR, NUM_CTA, FECHA_ALTA, NOMBRE_CTA, DIREC_CTA, POBLA_CTA, SALDO_DEBE, SALDO_HABER)  
    VALUES(cuentas.getCodBanco, cuentas.getCodSucur, cuentas.getNumCta, cuentas.getFechaAlta, cuentas.getNombreCta, cuentas.getDirectCta, cuentas.getPoblaCta, cuentas.getSaldoDebe, cuentas.getSaldoHaber);

  IF SQL%ROWCOUNT = 0 THEN
    RAISE e_noInsert;
  END IF;
  
  
  EXCEPTION 
    WHEN e_noInsert THEN
      RAISE_APPLICATION_ERROR(-20000, 'NO SE HA PODIDO INSERTAR EN TABLA CUENTAS');
      
    WHEN OTHERS THEN
      RAISE_APPLICATION_ERROR(-20000, 'HA HABIDO UN ERROR: - ' || SQLCODE || ' -ERROR- ' || SQLERRM); 
      
END INSERT_CUENTAS;
/

CREATE OR REPLACE PROCEDURE UPDATE_CUENTAS(cuentas CUENTAS_OBJ)
  IS
    e_noUpdate EXCEPTION;
  BEGIN 
    UPDATE CUENTAS
      SET FECHA_ALTA = cuentas.getFechaAlta, NOMBRE_CTA = cuentas.getNombreCta, DIREC_CTA = cuentas.getDirectCta, POBLA_CTA = cuentas.getPoblaCta, SALDO_DEBE = cuentas.getSaldoDebe, SALDO_HABER = cuentas.getSaldoHaber
      WHERE COD_BANCO = cuentas.getCodBanco AND COD_SUCUR = cuentas.getCodSucur AND NUM_CTA = cuentas.getNumCta;
    
  IF SQL%ROWCOUNT = 0 THEN
    RAISE e_noUpdate;
  END IF;
  
  
  EXCEPTION 
    WHEN e_noUpdate THEN
      RAISE_APPLICATION_ERROR(-20000, 'NO SE HA PODIDO ACTUALIZAR EN TABLA CUENTAS');
      
    WHEN OTHERS THEN
      RAISE_APPLICATION_ERROR(-20000, 'HA HABIDO UN ERROR: - ' || SQLCODE || ' -ERROR- ' || SQLERRM); 
      

END UPDATE_CUENTAS;
/

CREATE OR REPLACE PROCEDURE DELETE_CUENTAS(
  v_cod_banco IN CUENTAS.COD_BANCO%TYPE,
  v_cod_sucur IN CUENTAS.COD_SUCUR%TYPE,
  v_num_cta IN CUENTAS.NUM_CTA%TYPE)
  IS
    e_noDelete EXCEPTION;
  BEGIN
    DELETE FROM CUENTAS
      WHERE COD_BANCO = v_cod_banco AND COD_SUCUR = v_cod_sucur AND NUM_CTA = v_num_cta;
     
  IF SQL%ROWCOUNT = 0 THEN
    RAISE e_noDelete;
  END IF;
   

  EXCEPTION 
    WHEN e_noDelete THEN
      RAISE_APPLICATION_ERROR(-20000, 'NO SE HA PODIDO BORRAR EN TABLA CUENTAS');
      
    WHEN OTHERS THEN
      RAISE_APPLICATION_ERROR(-20000, 'HA HABIDO UN ERROR: - ' || SQLCODE || ' -ERROR- ' || SQLERRM); 
      
END DELETE_CUENTAS;
/

-- MOVIMIENTOS_OBJ
CREATE OR REPLACE PROCEDURE INSERT_MOVIMIENTOS(movimiento MOVIMIENTOS_OBJ)
  IS
    e_noInsert EXCEPTION;
  BEGIN 
  INSERT INTO MOVIMIENTOS (COD_BANCO, COD_SUCUR, NUM_CTA, FECHA_MOV, TIPO_MOV, IMPORTE)  
    VALUES(movimiento.getCodBanco, movimiento.getCodSucur, movimiento.getNumCta, movimiento.getFechaMov, movimiento.getTipoMov, movimiento.getImporte);

  IF SQL%ROWCOUNT = 0 THEN
    RAISE e_noInsert;
  END IF;
  
  
  EXCEPTION 
    WHEN e_noInsert THEN
      RAISE_APPLICATION_ERROR(-20000, 'NO SE HA PODIDO INSERTAR EN TABLA MOVIMIENTOS');
      
    WHEN OTHERS THEN
      RAISE_APPLICATION_ERROR(-20000, 'HA HABIDO UN ERROR: - ' || SQLCODE || ' -ERROR- ' || SQLERRM); 
      
END INSERT_MOVIMIENTOS;
/

/*
UPDATE Y DELETE de movimientos es imposible si la tabla original no tiene PK

CREATE OR REPLACE PROCEDURE UPDATE_MOVIMIENTOS(movimiento MOVIMIENTOS_OBJ)
  IS
    e_noUpdate EXCEPTION;
  BEGIN 
    UPDATE MOVIMIENTOS 
      SET TIPO_MOV = movimiento.getTipoMov, IMPORTE = movimiento.getImporte  
      WHERE COD_BANCO = movimiento.getCodBanco AND COD_SUCUR = movimiento.getCodSucur AND NUM_CTA = movimiento.getNumCta AND FECHA_MOV = movimiento.getFechaMov;
    
  IF SQL%ROWCOUNT = 0 THEN
    RAISE e_noUpdate;
  END IF;
  
  
  EXCEPTION 
    WHEN e_noUpdate THEN
      RAISE_APPLICATION_ERROR(-20000, 'NO SE HA PODIDO ACTUALIZAR EN TABLA MOVIMIENTOS');
      
    WHEN OTHERS THEN
      RAISE_APPLICATION_ERROR(-20000, 'HA HABIDO UN ERROR: - ' || SQLCODE || ' -ERROR- ' || SQLERRM); 
      
END UPDATE_MOVIMIENTOS;
/

CREATE OR REPLACE PROCEDURE DELETE_MOVIMIENTOS(
  v_cod_banco IN MOVIMIENTOS.COD_BANCO%TYPE,
  v_cod_sucur IN MOVIMIENTOS.COD_SUCUR%TYPE,
  v_num_cta IN MOVIMIENTOS.NUM_CTA%TYPE,
  v_fecha_mov IN MOVIMIENTOS.FECHA_MOV%TYPE)
  IS
    e_noDelete EXCEPTION;
  BEGIN
    DELETE FROM MOVIMIENTOS
      WHERE COD_BANCO = v_cod_banco AND COD_SUCUR = v_cod_sucur AND NUM_CTA = v_num_cta AND FECHA_MOV = v_fecha_mov;
     
  IF SQL%ROWCOUNT = 0 THEN
    RAISE e_noDelete;
  END IF;
   

  EXCEPTION 
    WHEN e_noDelete THEN
      RAISE_APPLICATION_ERROR(-20000, 'NO SE HA PODIDO BORRAR EN TABLA MOVIMIENTOS');
      
    WHEN OTHERS THEN
      RAISE_APPLICATION_ERROR(-20000, 'HA HABIDO UN ERROR: - ' || SQLCODE || ' -ERROR- ' || SQLERRM); 
      
END DELETE_MOVIMIENTOS;
/

*/

REM *** CREACION DE TRIGGERS ***

CREATE OR REPLACE TRIGGER BANCOS_BEFORE_TR 
  BEFORE INSERT OR UPDATE OR DELETE
    ON BANCOS 
    FOR EACH ROW 
    DECLARE
      -- PRAGMA AUTONOMOUS_TRANSACTION;
      v_poblacion_bancos NUMBER;
      v_cod_banco NUMBER;
      e_PK_COD_BANCO_EXISTE EXCEPTION;
      e_PK_COD_BANCO_MODIFICAR EXCEPTION;
      e_POBLACION_NO_EXISTE EXCEPTION;

    BEGIN
      IF INSERTING THEN
        SELECT COUNT(*) INTO v_cod_banco FROM BANCOS WHERE COD_BANCO = :NEW.COD_BANCO;
        IF v_cod_banco > 0 THEN
          RAISE e_PK_COD_BANCO_EXISTE;
        ELSE
            SELECT COUNT(*) INTO v_poblacion_bancos FROM BANCOS WHERE POBLACION LIKE :NEW.POBLACION;
          IF v_poblacion_bancos = 0 THEN
            RAISE e_POBLACION_NO_EXISTE;
          END IF;
        END IF;
      END IF;

      IF UPDATING THEN
        IF :OLD.COD_BANCO <> :NEW.COD_BANCO THEN
          RAISE e_PK_COD_BANCO_MODIFICAR;
        ELSE
          SELECT COUNT(*) INTO v_cod_banco FROM BANCOS WHERE COD_BANCO = :NEW.COD_BANCO;
          IF v_cod_banco > 0 THEN
            SELECT COUNT(*) INTO v_poblacion_bancos FROM BANCOS WHERE POBLACION LIKE :NEW.POBLACION;
            IF v_poblacion_bancos = 0 THEN
              RAISE e_POBLACION_NO_EXISTE;
            END IF;
          ELSE
            RAISE NO_DATA_FOUND;
          END IF;
        END IF;
      END IF;
      
      IF DELETING THEN
        SELECT COUNT(*) INTO v_cod_banco FROM BANCOS WHERE COD_BANCO = :OLD.COD_BANCO;
        IF v_cod_banco = 0 THEN
          RAISE NO_DATA_FOUND;
        ELSE
          DELETE FROM SUCURSALES WHERE COD_BANCO = :OLD.COD_BANCO;  
        END IF;
      END IF;

    EXCEPTION 
      WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20000,'EL COD_BANCO INTRODUCIDO NO EXISTE');
      WHEN e_PK_COD_BANCO_EXISTE THEN
        RAISE_APPLICATION_ERROR(-20000,'EL COD_BANCO INTRODUCIDO YA EXISTE');
      WHEN e_PK_COD_BANCO_MODIFICAR THEN
        RAISE_APPLICATION_ERROR(-20000,'EL COD_BANCO NO SE PUEDE MODIFICAR');
      WHEN e_POBLACION_NO_EXISTE THEN
        RAISE_APPLICATION_ERROR(-20000,'HA DE INTRODUCIR UNA POBLACION DE LAS EXISTENTES');
END;
/

CREATE OR REPLACE TRIGGER SUCURSALES_BEFORE_TR
  BEFORE INSERT OR UPDATE OR DELETE
  ON SUCURSALES
  FOR EACH ROW
  DECLARE
    -- PRAGMA AUTONOMOUS_TRANSACTION;
    v_cod_banco NUMBER;
    v_cod_banco_sucur NUMBER;
    v_localidad_bancos NUMBER;
    e_PK_COD_SUCUR_EXISTE EXCEPTION;
    e_PK_COD_BANCO_SUCUR_EXISTE EXCEPTION;
    e_PK_COD_BANCO_SUCUR_MOD EXCEPTION;
    e_LOCALIDAD_NO_EXISTE EXCEPTION;

  BEGIN
    IF INSERTING THEN
      SELECT COUNT(*) INTO v_cod_banco FROM BANCOS WHERE COD_BANCO = :NEW.COD_BANCO;
      IF v_cod_banco > 0 THEN
        SELECT COUNT(*) INTO v_cod_banco_sucur FROM SUCURSALES WHERE COD_BANCO = :NEW.COD_BANCO AND COD_SUCUR = :NEW.COD_SUCUR;
        IF v_cod_banco_sucur > 0 THEN
          RAISE e_PK_COD_BANCO_SUCUR_EXISTE;
        END IF;
      ELSE 
        RAISE NO_DATA_FOUND;
      END IF;
    END IF;

    IF UPDATING THEN 
      IF :OLD.COD_BANCO <> :NEW.COD_BANCO OR :OLD.COD_SUCUR <> :NEW.COD_SUCUR THEN
        RAISE e_PK_COD_BANCO_SUCUR_MOD;
      ELSE
        SELECT COUNT(*) INTO v_cod_banco_sucur FROM SUCURSALES WHERE COD_BANCO = :NEW.COD_BANCO AND COD_SUCUR = :NEW.COD_SUCUR;
        IF v_cod_banco_sucur > 0 THEN
          SELECT COUNT(*) INTO v_localidad_bancos FROM SUCURSALES WHERE LOC_SUC LIKE :NEW.LOC_SUC;
            IF v_localidad_bancos = 0 THEN
              RAISE e_LOCALIDAD_NO_EXISTE;
            END IF;
        ELSE
          RAISE NO_DATA_FOUND;
        END IF;
      END IF;
    END IF;

    IF DELETING THEN 
      SELECT COUNT(*) INTO v_cod_banco_sucur FROM SUCURSALES WHERE COD_BANCO = :OLD.COD_BANCO AND COD_SUCUR = :OLD.COD_SUCUR;
      IF v_cod_banco_sucur = 0 THEN
        RAISE NO_DATA_FOUND;
      ELSE
        DELETE FROM CUENTAS WHERE COD_BANCO = :OLD.COD_BANCO AND COD_SUCUR = :OLD.COD_SUCUR;
      END IF;
    END IF;

  EXCEPTION 
    WHEN NO_DATA_FOUND THEN
      RAISE_APPLICATION_ERROR(-20000,'EL COD_BANCO Y/O COD_SUCUR INTRODUCIDO NO EXISTE');
    WHEN e_PK_COD_BANCO_SUCUR_EXISTE THEN
      RAISE_APPLICATION_ERROR(-20000,'EL COD_BANCO Y/O COD_SUCUR INTRODUCIDO EXISTE, NO SE PUEDEN SOBRESCRIBIR');
    WHEN e_PK_COD_BANCO_SUCUR_MOD THEN
    RAISE_APPLICATION_ERROR(-20000,'EL COD_BANCO Y/O COD_SUCUR NO SE PUEDEN MODIFICAR');
    WHEN e_LOCALIDAD_NO_EXISTE THEN
        RAISE_APPLICATION_ERROR(-20000,'HA DE INTRODUCIR UNA LOCALIDAD DE LAS EXISTENTES');
END;
/

CREATE OR REPLACE TRIGGER CUENTAS_BEFORE_TR
  BEFORE INSERT OR UPDATE OR DELETE
  ON CUENTAS
  FOR EACH ROW
  DECLARE
    -- PRAGMA AUTONOMOUS_TRANSACTION;
    v_cod_banco NUMBER;
    v_cod_sucur NUMBER;
    v_num_cuenta NUMBER;
    v_saldos NUMBER;
    e_DELETE_SIN_SALDO_0 EXCEPTION;
    e_PK_COD_SUCUR_EXISTE EXCEPTION;
    e_PK_NUM_CTA_EXISTE EXCEPTION;
    e_PK_COD_BAN_SUCUR_NCTA_EXISTE EXCEPTION;
    e_PK_COD_BAN_SUCUR_NCTA_MOD EXCEPTION;

  BEGIN
    IF INSERTING THEN
      SELECT COUNT(*) INTO v_cod_banco FROM BANCOS WHERE COD_BANCO = :NEW.COD_BANCO;
      SELECT COUNT(*) INTO v_cod_sucur FROM SUCURSALES WHERE COD_BANCO = :NEW.COD_BANCO AND COD_SUCUR = :NEW.COD_SUCUR;
      IF v_cod_banco > 0 AND v_cod_sucur > 0 THEN
        SELECT COUNT(*) INTO v_cod_banco FROM CUENTAS WHERE COD_BANCO = :NEW.COD_BANCO AND COD_SUCUR = :NEW.COD_SUCUR AND NUM_CTA = :NEW.NUM_CTA;
        IF v_cod_banco > 0 THEN
          RAISE e_PK_COD_BAN_SUCUR_NCTA_EXISTE;
        END IF;
      END IF;
      ELSE
        RAISE NO_DATA_FOUND;
    END IF;

    IF UPDATING THEN 
      IF :OLD.COD_BANCO <> :NEW.COD_BANCO OR :OLD.COD_SUCUR <> :NEW.COD_SUCUR OR :OLD.NUM_CTA <> :NEW.NUM_CTA THEN
        RAISE e_PK_COD_BAN_SUCUR_NCTA_MOD;
      ELSE
      SELECT COUNT(*) INTO v_cod_banco FROM CUENTAS WHERE COD_BANCO = :NEW.COD_BANCO AND COD_SUCUR = :NEW.COD_SUCUR AND NUM_CTA = :NEW.NUM_CTA;
      IF v_cod_banco > 0 THEN
          RAISE e_PK_COD_BAN_SUCUR_NCTA_EXISTE;
        END IF;
      END IF;
    END IF;

    IF DELETING THEN 
      SELECT COUNT(*) INTO v_cod_banco FROM CUENTAS WHERE COD_BANCO = :OLD.COD_BANCO AND COD_SUCUR = :OLD.COD_SUCUR AND NUM_CTA = :OLD.NUM_CTA;
      IF v_cod_banco > 0 THEN
        SELECT COUNT(*) INTO v_saldos FROM CUENTAS WHERE COD_BANCO = :OLD.COD_BANCO AND COD_SUCUR = :OLD.COD_SUCUR AND NUM_CTA = :OLD.NUM_CTA;
        IF v_saldos > 0 THEN
          RAISE e_DELETE_SIN_SALDO_0;
        END IF;
        DELETE FROM MOVIMIENTOS WHERE COD_BANCO = :OLD.COD_BANCO AND COD_SUCUR = :OLD.COD_SUCUR AND NUM_CTA = :OLD.NUM_CTA;
      ELSE 
        RAISE NO_DATA_FOUND;
      END IF;
    END IF;

  EXCEPTION 
    WHEN NO_DATA_FOUND THEN
      RAISE_APPLICATION_ERROR(-20000,'EL COD_BANCO, COD_SUCUR Y/O NUM_CTA INTRODUCIDO NO EXISTE');
    WHEN e_PK_COD_BAN_SUCUR_NCTA_EXISTE THEN
      RAISE_APPLICATION_ERROR(-20000,'EL COD_BANCO, COD_SUCUR Y/O NUM_CTA INTRODUCIDO EXISTE, NO SE PUEDEN SOBRESCRIBIR');
    WHEN e_PK_COD_BAN_SUCUR_NCTA_MOD THEN
      RAISE_APPLICATION_ERROR(-20000,'EL COD_BANCO, COD_SUCUR Y/O NUM_CTA INTRODUCIDO EXISTE, NO SE PUEDEN MODIFICAR');
    WHEN e_DELETE_SIN_SALDO_0 THEN
      RAISE_APPLICATION_ERROR(-20000,'NO PUEDE BORRAR UNA CUENTA CON SALDO MAYOR QUE 0');
END;
/

CREATE OR REPLACE TRIGGER MOVIMIENTOS_BEFORE_TR
  BEFORE INSERT OR UPDATE OR DELETE
  ON MOVIMIENTOS
  FOR EACH ROW
  DECLARE
    -- PRAGMA AUTONOMOUS_TRANSACTION;
    v_cod_banco NUMBER;
    v_cod_sucur NUMBER;
    v_num_cuenta NUMBER;
    e_PK_COD_BANCO_EXISTE EXCEPTION;
    e_PK_COD_SUCUR_EXISTE EXCEPTION;
    e_PK_NUM_CTA_EXISTE EXCEPTION;
    e_PK_COD_BAN_SUCUR_NCTA_EXISTE EXCEPTION;
    e_MOV_FUTURO EXCEPTION;
    e_POBLACION_DISTINTA EXCEPTION;

  BEGIN
    IF INSERTING THEN
      SELECT COUNT(*) INTO v_num_cuenta FROM CUENTAS WHERE COD_BANCO = :NEW.COD_BANCO AND COD_SUCUR = :NEW.COD_SUCUR AND COD_SUCUR = :NEW.COD_SUCUR;
      IF v_num_cuenta > 0 THEN
        IF :NEW.FECHA_MOV > SYSDATE THEN
          RAISE e_MOV_FUTURO;
        END IF;
        ELSE 
        RAISE NO_DATA_FOUND;
      END IF;
    END IF;

  EXCEPTION 
    WHEN NO_DATA_FOUND THEN
      RAISE_APPLICATION_ERROR(-20000,'EL COD_BANCO, COD_SUCUR Y/O NUM_CTA INTRODUCIDO NO EXISTE');
    WHEN e_PK_COD_BAN_SUCUR_NCTA_EXISTE THEN
      RAISE_APPLICATION_ERROR(-20000,'EL COD_BANCO, COD_SUCUR Y/O NUM_CTA INTRODUCIDO EXISTE, NO SE PUEDEN SOBRESCRIBIR');
    WHEN e_MOV_FUTURO THEN 
      RAISE_APPLICATION_ERROR(-20000,'NO SE PUEDEN REALIZAR MOVIMIENTOS A FUTURO');
    WHEN e_POBLACION_DISTINTA THEN 
      RAISE_APPLICATION_ERROR(-20000,'NO SE HACER MOVIMIENTOS A CUENTAS CON POBLACION DISTINTA A LA EXISTENTE');
END;
/
